"use client"
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AOS from 'aos'
import 'aos/dist/aos.css'
import { useEffect } from 'react';



const metadata: Metadata = {
  title: 'Rwikistat Web App',
  description: 'Generated by create next app',
  verification: { google: "11Xtq9cHvNyWjdeZUEQJriO-737INPZVdPCkjC8LTpc" }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  useEffect(() => {
    AOS.init({
      once: true,
      duration: 700,
      easing: 'ease-out-cubic',
    })
  })

  return (
    <html lang="en">
      <body className={`font-inter antialiased bg-white text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
      </body>
    </html>
  )
}
